### ISSUE TITLE
TypeError: _onGoingScrolls$get is undefined

### ISSUE THREAD

**Issue by pattwala** [josepot/react-redux-scroll#1] opened 2017-04-03 01:21 UTC
I'm getting the error, `TypeError: _onGoingScrolls$get is undefined` on a state change when my scrollable components are unmounting. I've added a console.log within the parent component's componentWillUnmount where I call window.removeEventListener(). Most times it unmounts all the scrollable components before a render occurs. But every so often it doesn't finish unmounting (an removing the event listeners) and it throws the error.  Unfortunately I can't consistently recreate the error.

The error occurs in scroll.js, at the 3rd line of the following function.

```
var clearEntry = function clearEntry(context, isCancellation) {
  var _onGoingScrolls$get = onGoingScrolls.get(context),
      animationId = _onGoingScrolls$get.animationId, // error on this line
      onEnd = _onGoingScrolls$get.onEnd;

  if (isCancellation) cancelAnimationFrame(animationId);
  onEnd(isCancellation);
  onGoingScrolls.delete(context);
};
```
Let me know what else I can provide to help debug this.

**Comment by pattwala** [comment] 2017-04-03 01:35
I modified the function to this and it seems to have solved the issue for me, but it may only be a band-aid solution:

```
var clearEntry = function clearEntry(context, isCancellation) {
  var _onGoingScrolls$get = onGoingScrolls.get(context);
  if(_onGoingScrolls$get) {
    var animationId = _onGoingScrolls$get.animationId,
    onEnd = _onGoingScrolls$get.onEnd;
    if (isCancellation) cancelAnimationFrame(animationId);
    onEnd(isCancellation);
  }

  onGoingScrolls.delete(context);
};
```

**Comment by josepot** [comment] 2017-04-03 14:16
Hi @pattwala !

Thanks for submitting this issue. I think that I know what the problem is. Could you please let the browser's version that you were using when you saw this issue?

The thing is that `onGoingScrolls` is a [WeakMap](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/WeakMap) but since not all browsers support them I wrote a [basic polyfill](https://github.com/josepot/react-redux-scroll/blob/master/src/utils/weakmap.js#L35) that should be used for those browsers that don't fully support `WeakMap`. The only reasonable explanation that I can find so far is that the browser that you are using does have a `window.WeakMap` but not a standard one, because a standard `WeakMap` should support `get`.

**Comment by josepot** [comment] 2017-04-03 14:46
Hi @pattwala !

Thank you so much for reporting this issue. If you could provide with a basic POC to reproduce this, that would be awesome. I'm trying to create one myself because I think that I have a clue of what it could be happening here, but I haven't managed to reproduce this yet.

In the meanwhile, though, could you please let me know if when this issue occurs the value of `context` is `undefined`?

Thanks a lot,

Josep

**Comment by josepot** [comment] 2017-04-03 15:18
Hi @pattwala !

A couple more questions:

- When this issue occurs is the value of `isCancellation` set to `true`?
- Does this issue happen while unmounting a `scrollToWhen` component that's inside of a "scrollabeArea"?
- Does it happen while you are unmounting and the scroll hasn't finished?

Thanks,

Josep

**Comment by pattwala** [comment] 2017-04-03 15:31
Hi! It was happening everywhere. I predominantly use Firefox (v. 52.0.2), but it was also happening in Chrome (Version 56.0.2924.87 (64-bit)). I’m on a Mac running OS X Sierra.

**Comment by pattwala** [comment] 2017-04-03 15:38
```
import React, {PropTypes} from 'react'; 
import { connect } from 'react-redux';
import { scrollToWhen } from 'react-redux-scroll';
import * as types from '../actions/actionTypes';
import $ from 'cash-dom'; //jquery alternative

//Import sub-components
import Hero from './Hero.jsx';
import Essay from './Essay.jsx';
import Works from './Works.jsx';
import Toolbar from './Toolbar.jsx';


// class Vertical extends React.Component {
var Vertical = React.createClass({

	render: function() {
		const v = this.props.vertical;
		const type = v.fields.type;
		const currentPage = this.props.currentPage;
		const isVerticalExpanded = (v.fields.path == currentPage.vertical) ? currentPage.verticalExpanded : false;
		let classes = v.fields.type + " vertical ";


		if(isVerticalExpanded) {
			classes += "expanded";
		}
		else if($("#" + v.fields.path).hasClass('expanded') && $("#" + v.fields.path).hasClass('collapsed')) {
			classes += "expanded collapsed";
		}


		return (
			<div id={this.props.vertical.fields.path} ref={(ref) => this.vertical = ref} className={classes}>
				{/* Hero */}
				<ScrollableHero key={`hero-${v.sys.id}`} vertical={v} />

				<div className="vertical-body">
					<Essay item={v} />
					{(type != "homepage") ? (
					<Works verticalID={v.sys.id} verticalName={this.props.vertical.fields.verticalTitle}/>
					) : (
					<div />
					)}
				</div>

				{/* Toolbar */}
				{(type != "homepage") ? (
				<Toolbar previousPage={this.props.previousPage} onButtonClick={this.props.onButtonClick} />
				) : (
				<div />
				)}
			</div>
		)
	},

	componentWillUnmount: function() {
		window.removeEventListener('scroll', this.handleScroll);
	},
	
	componentDidMount: function() {
		window.addEventListener('scroll', this.handleScroll);
	},

	handleScroll: function(event) {
		let $vertical = $($(this.vertical)[0]);
		let $heroContent = $($vertical.find(".vertical-hero-content"));
		let scrollDistance = window.pageYOffset;
		let halfWindowHeight = Math.floor(window.innerHeight/2);
		let topOffset = $vertical.offset().top;
		
		//Handle opacity of Vertical Hero content
		if(scrollDistance + halfWindowHeight >= topOffset && scrollDistance <= topOffset) {
			$heroContent.css("opacity", ((scrollDistance - topOffset) + halfWindowHeight) / halfWindowHeight);
		}
		else if (scrollDistance > topOffset) {
			$heroContent.css("opacity", 1);
		}

	}
});

Vertical.propTypes = {
	lang: PropTypes.string.isRequired, // from mapStateToProps
	currentPage: PropTypes.object.isRequired, // from mapStateToProps
	previousPage: PropTypes.string.isRequired, // from mapStateToProps

	vertical: PropTypes.object.isRequired
}

const ScrollableHero = scrollToWhen(
	(action, props) => {
		return ((action.type === types.COLLAPSE_VERTICAL || action.type === types.EXPAND_VERTICAL) && action.vertical.sys.id === props.vertical.sys.id)
	},
	null,
	{ duration: 100, yMargin: 0 }
)(Hero);

const mapStateToProps = (state, ownProps) => {
	return {
		lang: state.lang,
		currentPage: state.currentPage,
		previousPage: (state.lang == "en") ? "/" : "/fr/"
	}
}

const mapDispatchToProps = (dispatch, ownProps) => {
	return {
		onButtonClick: () => {
			dispatch({type: types.COLLAPSE_VERTICAL, vertical: ownProps.vertical} )
		}
	}
}

export default connect(mapStateToProps, mapDispatchToProps)(Vertical);

```

**Comment by pattwala** [comment] 2017-04-03 15:45
**When this issue occurs is the value of isCancellation set to true?**
- I don't know.

**Does this issue happen while unmounting a scrollToWhen component that's inside of a "scrollabeArea"?**
- the scrollToWhen component is not inside of a scrollableArea

**Does it happen while you are unmounting and the scroll hasn't finished?**
- theoretically there shouldn't be any scroll happening as the action that was dispatched wasn't relevant to the scroll event. It seems as though the DOM re-rendered before all of the scrollToWhen components were unmounted.

**Comment by pattwala** [comment] 2017-04-03 15:47
I’d like to send you a link to a website that’s currently in development where you can recreate the error. Just want to make sure you don’t share it and just use it for debugging purposes.

Best,
Pramesh

—
Pramesh Attwala
Partner + Technical Director, GRNDWRK
http://www.grndwrk.ca
647.300.7104
@ttwala

**Comment by josepot** [comment] 2017-04-03 16:58
Hi @pattwala !

I just merged a PR that I think that should solve this issue. Could you please confirm that the latest version solves this issue? (`npm update` or `yarn upgrade react-redux-scroll`)

Thanks a lot for your help!

**Comment by pattwala** [comment] 2017-04-03 18:21
@josepot I think you got it. I went through the same scenario I walked you through and can't recreate the problem anymore. Thanks for fixing the issue so promptly!

**Closed as completed** 2017-04-03 18:24 UTC
Labels: bug
