### ISSUE TITLE
scrollToWhen jump to a different scrollable component when already at the scrolled position

### ISSUE THREAD

**Issue by pattwala** [josepot/react-redux-scroll#3] opened 2017-04-06 15:27 UTC
Hi @josepot,

I've got a new issue for you. On the same page I showed you, I have a different scrollToWhen component below the already existing one. There is a click event that toggles the render of a child component within the second scrollToWhen, so it's either in the DOM or it's not. Here's the flow:

1) Click button to render child component - element is rendered and scrolls to correct position
2) Immediately click button again - child component is removed from DOM and screen should stay in place because there's no where to scroll to... but, instead it jumps up to the first scrollToWhen component.

I'm sure observing this behavior would be helpful to you, so let me know and I can make it available to see.

Thanks.

**Comment by josepot** [comment] 2017-04-06 16:17
Hi @pattwala !

If I understood you correctly, I think that this is not a real issue (maybe I'm missing something, though).

If I understood this correctly you have different instances of a `scrollToWhen` component that are ["competing" for the same action](https://github.com/josepot/react-redux-scroll#--what-happens-when-more-than-one-scroll-tries-to-take-place-as-a-result-of-the-latest-action-that-was-dispatched).

You say: 

> instead it jumps up to the first scrollToWhen component

I don't see this as an issue if the scrollToWhen pattern of that component resolves to `true` for the action that got dispatched... So, if the problem is that there are different instances "competing" over the same action pattern, you should try to make sure that doesn't happen by adding more conditions to [the pattern](https://github.com/josepot/react-redux-scroll#--pattern-string--function--array). So that whenever an action gets dispatched, just one instance (or none) of that `scrollToWhen` component will try to get the scroll.

For example, lets say that I have a `scrollToWhen` component like this:

```
const ScrollableTitle = scrollToWhen('GO_TO_TITLE')('h1');
```

And then I do:
```
<ScrollableTitle>First Title</ScrollableTitle>
<p>Whatever</p>
<ScrollableTitle>First Title 2</ScrollableTitle>
<p>Whatever2</p>
```

Now, what will happen when an action type `GO_TO_TITLE` gets triggered? There will be 2 different instances that want the scroll... That's not good. So, instead I could do something like:

```
const ScrollableTitle = scrollToWhen(
  (action, props) => (action.type === 'GO_TO_TITLE' && action.titleId === props.id)
)('h1'); 
```

And use it like this:
```
<ScrollableTitle id='first'>First Title</ScrollableTitle>
<p>Whatever</p>
<ScrollableTitle id='second'>First Title 2</ScrollableTitle>
<p>Whatever2</p>
```

And make sure that when I trigger the `GO_TO_TITLE` action I include the `titleId` property.

For the pattern function you can use: the action, the props of the component, the new state and the old state... So hopefully with all those inputs you should be able to create a condition that prevents race conditions between the different instances of the component.

**Comment by pattwala** [comment] 2017-04-06 16:19
Except it's a different action that's triggering the scrolltowhen.

**Comment by josepot** [comment] 2017-04-06 16:21
> Except it's a different action that's triggering the scrolltowhen.

😳 

Are you sure?

I would like to see a POC of that.

If that's the case, then, yep, this is an issue 😅

**Comment by josepot** [comment] 2017-04-06 21:45
Closing this, because after debugging the issue with @pattwala it turns out that the problem was unrelated with this library.

**Closed as completed by josepot** 2017-04-06 21:45 UTC
